openapi: 3.0.3
info:
  title: Unpatched Server API
  version: 1.0.0
  description: |-
    Unpatched Server API
    * All timestamps are in UTC
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Alexander Kunde
    email: alexander@apimeister.com
externalDocs:
  description: Find out more about Unpatched Server
  url: https://github.com/apimeister/unpatched-server
servers:
- url: http://localhost:3000/api/v1
tags:
  - name: executions
    description: Everything about your executions
    externalDocs:
      description: Find out more
      url: https://github.com/apimeister/unpatched-server
paths:
  /agents:
    get:
      summary: get all agents
      responses:
        200:
          description: all agents
  /agents/{agent_id}:
    get:
      summary: get agent information
      parameters:
        - in: path
          name: agent_id
          schema:
            type: string
            format: uuid v4
          required: true
          description: agent id
      responses:
        200:
          description: agent information
  /executions:
    get:
      tags:
        - executions
      summary:  Retrieve list of hosts
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Execution'
        404:
          description: No executions found
    post:
      tags:
        - executions
      summary: Create a new execution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Execution'
      responses:
        '201':
          description: Execution created successfully
        '400':
          description: Bad request
    delete:
      tags:
        - executions
      summary: Delete all executions
      responses:
        '200':
          description: Executions deleted successfully
        '403':
          description: Forbidden request
  /executions/{execution_id}:
    get:
      tags:
        - executions
      summary: get execution information
      parameters:
        - in: path
          name: execution_id
          schema:
            type: string
            format: uuid
          required: true
          description: execution id
      responses:
        200:
          description: execution information
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Execution'
        404:
          description: no execution found with this id
    delete:
      tags:
        - executions
      summary: delete execution
      parameters:
        - in: path
          name: execution_id
          schema:
            type: string
            format: uuid
          required: true
          description: execution id
      responses:
        200:
          description: execution deleted
        403:
          description: no execution found with this id or cannot be deleted
      responses:
        '200':
          description: Success
        '403':
          description: Forbidden
components:
  schemas:
    Execution:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        request:
          type: string
          format: date-time
        response:
          type: string
          format: date-time
          nullable: true
          readOnly: true
        host_id:
          type: string
          format: uuid
        script_id:
          type: string
          format: uuid
        sched_id:
          type: string
          format: uuid
        created:
          type: string
          format: date-time
          readOnly: true
        output:
          type: string
          nullable: true
          readOnly: true
          example: hello world
        script_id:
          type: string
          example: da77836d-1f63-4e30-b753-fe35784af63c