openapi: 3.0.3
info:
  title: Unpatched Server API
  version: 1.0.0
  description: |-
    Unpatched Server API
    * All timestamps are in UTC
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Alexander Kunde
    email: alexander@apimeister.com
externalDocs:
  description: Find out more about Unpatched Server
  url: https://github.com/apimeister/unpatched-server
servers:
- url: http://localhost:3000/api/v1
tags:
  - name: executions
    description: Everything about your executions
    externalDocs:
      description: Find out more
      url: https://github.com/apimeister/unpatched-server
  - name: scripts
    description: Everything about your scripts
    externalDocs:
      description: Find out more
      url: https://github.com/apimeister/unpatched-server
paths:
  /hosts:
    get:
      summary: Retrieve list of hosts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Host'
        '404':
          description: No hosts found

  /executions:
    get:
      tags:
        - executions
      summary:  Retrieve list of hosts
      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Execution'
        404:
          description: No executions found
    post:
      tags:
        - executions
      summary: Create a new execution
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Execution'
      responses:
        '201':
          description: Execution created successfully
        '400':
          description: Bad request
    delete:
      tags:
        - executions
      summary: Delete all executions
      responses:
        '200':
          description: Executions deleted successfully
        '403':
          description: Forbidden request
  /executions/{execution_id}:
    get:
      tags:
        - executions
      summary: get execution information
      parameters:
        - in: path
          name: execution_id
          schema:
            type: string
            format: uuid
          required: true
          description: execution id
      responses:
        200:
          description: execution information
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Execution'
        404:
          description: no execution found with this id
    delete:
      tags:
        - executions
      summary: delete execution
      parameters:
        - in: path
          name: execution_id
          schema:
            type: string
            format: uuid
          required: true
          description: execution id
      responses:
        200:
          description: execution deleted
        403:
          description: no execution found with this id or cannot be deleted
  /scripts:
    get:
      tags:
        - scripts
      summary: Retrieve list of scripts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Script'
        '404':
          description: No scripts found
    delete:
      tags:
        - scripts
      summary: Delete all scripts
      responses:
        '200':
          description: Scripts deleted successfully
        '403':
          description: Forbidden request
    post:
      tags:
        - scripts
      summary: Create a new script
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Script'
      responses:
        '201':
          description: Script created successfully
        '400':
          description: Bad request
  /scripts/{script_id}:
    get:
      tags:
        - scripts
      summary: Get a single script by ID
      parameters:
        - in: path
          name: script_id
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the script to retrieve
      responses:
        '200':
          description: Script retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Script'
        '404':
          description: Script not found
    delete:
      tags:
        - scripts
      summary: Delete a single script by ID
      parameters:
        - in: path
          name: script_id
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the script to delete
      responses:
        '200':
          description: Script deleted successfully
        '403':
          description: Forbidden (delete failed)   
components:
  schemas:
    Execution:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        request:
          type: string
          format: date-time
        response:
          type: string
          format: date-time
          nullable: true
          readOnly: true
        host_id:
          type: string
          format: uuid
        script_id:
          type: string
          format: uuid
        sched_id:
          type: string
          format: uuid
        created:
          type: string
          format: date-time
          readOnly: true
        output:
          type: string
          nullable: true
          readOnly: true
          example: hello world
    Host:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        alias:
          type: string
        attributes:
          type: array
          items:
            type: string
        ip:
          type: string
        last_pong:
          type: string
          format: date-time
    Schedule:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        script_id:
          type: string
          format: uuid
        attributes:
          type: array
          items:
            type: string
        cron:
          type: string
        active:
          type: boolean
    Script:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
        version:
          type: string
        output_regex:
          type: string
          format: regex
        labels:
          type: array
          items:
            type: string
        timeout:
          type: string
        script_content:
          type: string