openapi: 3.0.1
info:
  title: Unpatched Server API
  version: 1.0.0
  description: a generated client for the Unpatched Server API
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Alexander Kunde
    email: alexander@apimeister.com
servers:
- url: https://localhost:3000/api/{version}
  variables:
    version:
      default: v1
      enum:
        - v1
paths:
  /agents:
    get:
      summary: get all agents
      operationId: getAllContext
      responses:
        200:
          description: status
  /agents/{agent_id}:
    get:
      summary: get agent information
      parameters:
        - in: path
          name: agent_id
          schema:
            type: string
            format: uuid
          required: true
          description: agent id
      responses:
        200:
          description: agent information