[package]
name = "monitoring-server"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["Alexander Kunde<alexander@apimeister.com>", "Jens Walter<jens@apimeister.com>"]

[dependencies]
axum = { git = "https://github.com/tokio-rs/axum", features = ["ws"] }
axum-extra = { git = "https://github.com/tokio-rs/axum", features = ["typed-header"] }
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
headers = "0.3"
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.19"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["fs", "trace"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
once_cell = "1"
clap = { version = "4", features = ["derive"] }


[[bin]]
name = "monitoring-server"
path = "src/main.rs"
