baseURL = 'http://unpatched.dev/'
languageCode = 'en-us'
title = 'Unpatched Server'

[menu]
  [[menu.main]]
    name = "OVERVIEW"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "AGENTS"
    url = "/agents"
    weight = 2
  [[menu.main]]
    name = "SCRIPTS"
    url = "/scripts"
    weight = 3
  [[menu.main]]
    name = "SCHEDULES"
    url = "/schedules"
    weight = 4
  [[menu.main]]
    name = "EXECUTIONS"
    url = "/executions"
    weight = 5
  [[menu.main]]
    name = "USERS"
    url = "/users"
    weight = 6
  [[menu.main]]
    name = "API"
    url = "/api"
    weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true