baseURL = 'http://unpatched.dev/'
languageCode = 'en-us'
title = 'Unpatched Server'

[menu]
  [[menu.main]]
    name = "OVERVIEW"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "NEXT"
    url = "/next"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true