name: Code Coverage

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable
      - name: Install cargo-llvm-cov and nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest,cargo-llvm-cov
      - name: Generate code coverage
        env:
          RUST_LOG: debug
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info nextest --no-fail-fast
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: lcov.info
          fail_ci_if_error: true