name: pr
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.rustup
          /usr/local/cargo
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install Rust
      run: rustup update stable
    - name: Add Musl Target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Run rustfmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all-targets -- -D warnings
    - uses: taiki-e/install-action@nextest
    - name: Cargo Test
      run: cargo nextest run --no-fail-fast
    - name: merge
      if: github.event_name == 'pull_request' && github.actor == 'dependabot[bot]'
      run: |
        gh pr merge --merge $GITHUB_HEAD_REF
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Compile
      run: |
        sudo apt-get install musl-tools
        cargo build --release --target x86_64-unknown-linux-musl;
        ldd target/x86_64-unknown-linux-musl/release/unpatched-server;
    - name: dtz upload
      if: github.ref_name == 'main'
      uses: DownToZero-cloud/objectstore-upload@main
      with:
        api_key: ${{ secrets.DTZ_API_KEY }}
        context_id: ${{ secrets.DTZ_CONTEXT_ID }}
        object_key: unpatched-server
        name: target/x86_64-unknown-linux-musl/release/unpatched-server