on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"
jobs:
  create-winlinux:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup
            /usr/local/cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        run: rustup update stable
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
      - uses: taiki-e/install-action@nextest
      - name: Cargo Test
        run: cargo nextest run --no-fail-fast
      - name: Install Targets
        run: |
          rustup target add x86_64-pc-windows-gnu x86_64-unknown-linux-musl x86_64-apple-darwin
          sudo apt install -y musl-tools gcc-mingw-w64
      - name: Compile
        run: |
          cargo build --release --target x86_64-pc-windows-gnu
          cargo build --release --target x86_64-unknown-linux-musl
      - name: Pack
        run: |
          tar -czvf unpatched-server_x86_64-unknown-linux-musl.tar.gz -C target/x86_64-unknown-linux-musl/release unpatched-server
          zip -jv unpatched-server_x86_64-pc-windows-gnu.zip target/x86_64-pc-windows-gnu/release/unpatched-server
          ls -lash
      - uses: actions/upload-artifact@v3
        with:
          name: winlinux
          path: |
            unpatched-server_x86_64-unknown-linux-musl.tar.gz
            unpatched-server_x86_64-pc-windows-gnu.zip
          if-no-files-found: error
  create-mac:
    runs-on:  macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.rustup
            /usr/local/cargo
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust
        run: rustup update stable
      - name: Run rustfmt
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
      - uses: taiki-e/install-action@nextest
      - name: Cargo Test
        run: cargo nextest run --no-fail-fast
      - name: Compile
        run:  cargo build --release
      - name: Pack
        run: 
          zip -jv unpatched-server_x86_64-apple-darwin.zip target/release/unpatched-server
      - uses: actions/upload-artifact@v3
        with:
          name: mac
          path: unpatched-server_x86_64-apple-darwin.zip
          if-no-files-found: error
  release:
    runs-on:  ubuntu-latest
    needs: ["create-winlinux", "create-mac"]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: winlinux
      - uses: actions/download-artifact@v3
        with:
          name: mac
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            unpatched-server_x86_64-unknown-linux-musl.tar.gz
            unpatched-server_x86_64-apple-darwin.zip
            unpatched-server_x86_64-pc-windows-gnu.zip
      